<?php

// N E C E S S A R Y   I N C L U D E S

include_once('classes/AskApi.php');
include_once('vendor/autoload.php');


// S E T T I N G S

$wiki = "wiki.local";

$elasticIndexDir = "/tmp/elasticindex";
$skosN3file = "/Users/thijs/Development/internship/skos/hzbwnature.n3"; 
# generated by /indexing/skos.n3.php
